// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBle0MzOSFv3jaa6XD1UTyy4o_S75Vr2y4',
    appId: '1:266707784168:web:3adeb9c0969d943a8ed45d',
    messagingSenderId: '266707784168',
    projectId: 'grocery-master-c0726',
    authDomain: 'grocery-master-c0726.firebaseapp.com',
    storageBucket: 'grocery-master-c0726.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6MqwrAGWxGVmyecsuKgWjS-XzgkxhN4U',
    appId: '1:266707784168:android:a497925d1c34a1c18ed45d',
    messagingSenderId: '266707784168',
    projectId: 'grocery-master-c0726',
    storageBucket: 'grocery-master-c0726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbguXlwcKAlqJ7abqpotMkjw-J5juoJk',
    appId: '1:266707784168:ios:4b6d9bc5270ae2a48ed45d',
    messagingSenderId: '266707784168',
    projectId: 'grocery-master-c0726',
    storageBucket: 'grocery-master-c0726.appspot.com',
    iosBundleId: 'com.example.grocerymaster',
  );
}
